// shopCatalog.js — the master list of cosmetic shop items.
//
// All items are COSMETIC ONLY. Nothing here can affect debate results, rank
// tokens, matchmaking, or grant any competitive advantage.
//
// Fields per item match the Firestore shopItems/{itemId} schema:
//   id, name, description, category, rarity, price, imageName, isAnimated,
//   rotationType ('daily' | 'weekly' | 'special' | 'permanent'), isLimited,
//   colorHex (optional), secondaryColorHex (optional, gradients),
//   effect (optional: 'shimmer' | 'glow' | 'rainbow' | 'pulse'),
//   bannerText (optional, badges), bannerColorHex (optional, badge gradient end)
//
// Categories: frame, usernameColor, badge.
// (Victory celebrations were removed from the shop.)
//
// `special` items are ultra-rare finds that only occasionally appear in a
// user's personal daily shop.
//
// Price guidance: daily 20-60, weekly 75-180, special 200-500.

const RARITY = {
  COMMON: 'common',
  RARE: 'rare',
  EPIC: 'epic',
  LEGENDARY: 'legendary',
  MYTHIC: 'mythic'
};

const CATALOG = [
  // ── Daily items (rotationType: 'daily', price 20-60) ──────────────────
  // Profile frames
  { id: 'frame_classic_gold', name: 'Classic Gold Frame', description: 'A clean champagne-gold ring for your avatar.', category: 'frame', rarity: RARITY.COMMON, price: 25, imageName: 'circle', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#C9A962' },
  { id: 'frame_emerald', name: 'Emerald Frame', description: 'A polished emerald avatar ring.', category: 'frame', rarity: RARITY.RARE, price: 40, imageName: 'circle', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#2FB67A' },
  { id: 'frame_crimson', name: 'Crimson Frame', description: 'A bold crimson avatar ring.', category: 'frame', rarity: RARITY.RARE, price: 40, imageName: 'circle', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#D95C5C' },
  { id: 'frame_sapphire', name: 'Sapphire Frame', description: 'A cool sapphire avatar ring.', category: 'frame', rarity: RARITY.COMMON, price: 25, imageName: 'circle', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#5C8AD9' },
  { id: 'frame_platinum', name: 'Platinum Frame', description: 'A sleek platinum avatar ring.', category: 'frame', rarity: RARITY.COMMON, price: 30, imageName: 'circle', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#B8C4D4' },
  { id: 'frame_amethyst', name: 'Amethyst Frame', description: 'A deep violet avatar ring with a soft inner glow.', category: 'frame', rarity: RARITY.RARE, price: 45, imageName: 'circle', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#9B6CE0', effect: 'glow' },
  { id: 'frame_onyx', name: 'Onyx Frame', description: 'A jet-black ring edged in silver.', category: 'frame', rarity: RARITY.RARE, price: 42, imageName: 'circle', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#3A3A44', secondaryColorHex: '#B8C4D4' },
  { id: 'frame_sunset', name: 'Sunset Frame', description: 'A warm orange-to-pink gradient ring.', category: 'frame', rarity: RARITY.RARE, price: 48, imageName: 'circle', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#FF8C5A', secondaryColorHex: '#E05C9A' },
  { id: 'frame_rose_gold', name: 'Rose Gold Frame', description: 'A blushing rose-gold ring with a champagne finish.', category: 'frame', rarity: RARITY.RARE, price: 45, imageName: 'circle', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#E8A9A0', secondaryColorHex: '#C9A962' },
  { id: 'frame_arctic', name: 'Arctic Frame', description: 'A glacial ice-blue ring with a frosty glow.', category: 'frame', rarity: RARITY.RARE, price: 44, imageName: 'snowflake', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#A8E4FF', secondaryColorHex: '#E8F7FF', effect: 'glow' },
  { id: 'frame_jade', name: 'Jade Frame', description: 'A smooth jade-stone avatar ring.', category: 'frame', rarity: RARITY.COMMON, price: 28, imageName: 'circle', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#4CB78A' },
  { id: 'frame_midnight', name: 'Midnight Frame', description: 'A deep indigo ring that fades into violet.', category: 'frame', rarity: RARITY.RARE, price: 40, imageName: 'moon.fill', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#2E3A8C', secondaryColorHex: '#6B5CE7' },
  { id: 'frame_bubblegum', name: 'Bubblegum Frame', description: 'A playful bubblegum-pink ring.', category: 'frame', rarity: RARITY.COMMON, price: 26, imageName: 'circle', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#FF8AC2' },
  { id: 'frame_copper', name: 'Copper Frame', description: 'A burnished copper ring with warm undertones.', category: 'frame', rarity: RARITY.COMMON, price: 24, imageName: 'circle', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#C97F4A' },
  { id: 'frame_storm', name: 'Storm Frame', description: 'A brooding slate ring streaked with silver.', category: 'frame', rarity: RARITY.RARE, price: 38, imageName: 'cloud.bolt.fill', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#5C6E8C', secondaryColorHex: '#9AB4D4' },
  { id: 'frame_neon_lime', name: 'Neon Lime Frame', description: 'An electric lime ring that hums with energy.', category: 'frame', rarity: RARITY.RARE, price: 42, imageName: 'circle', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#B4FF3D', effect: 'glow' },

  // Username colors
  { id: 'color_gold', name: 'Gold Name', description: 'Show your username in champagne gold.', category: 'usernameColor', rarity: RARITY.COMMON, price: 20, imageName: 'textformat', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#C9A962' },
  { id: 'color_violet', name: 'Violet Name', description: 'A rich violet username color.', category: 'usernameColor', rarity: RARITY.RARE, price: 35, imageName: 'textformat', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#9B6CE0' },
  { id: 'color_teal', name: 'Teal Name', description: 'A crisp teal username color.', category: 'usernameColor', rarity: RARITY.COMMON, price: 20, imageName: 'textformat', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#39C0B3' },
  { id: 'color_rose', name: 'Rose Name', description: 'A soft rose username color.', category: 'usernameColor', rarity: RARITY.COMMON, price: 22, imageName: 'textformat', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#E07A9A' },
  { id: 'color_ember', name: 'Ember Name', description: 'A fiery orange-to-red gradient name.', category: 'usernameColor', rarity: RARITY.RARE, price: 40, imageName: 'textformat', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#FF9A3D', secondaryColorHex: '#E0453D' },
  { id: 'color_ocean', name: 'Ocean Name', description: 'A cool blue-to-teal gradient name.', category: 'usernameColor', rarity: RARITY.RARE, price: 40, imageName: 'textformat', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#4D8DE0', secondaryColorHex: '#39C0B3' },
  { id: 'color_crimson', name: 'Crimson Name', description: 'A striking crimson username color.', category: 'usernameColor', rarity: RARITY.COMMON, price: 20, imageName: 'textformat', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#D9455C' },
  { id: 'color_mint', name: 'Mint Name', description: 'A fresh mint-green username color.', category: 'usernameColor', rarity: RARITY.COMMON, price: 20, imageName: 'textformat', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#7AE0B8' },
  { id: 'color_sky', name: 'Sky Name', description: 'A bright daytime-sky username color.', category: 'usernameColor', rarity: RARITY.COMMON, price: 22, imageName: 'textformat', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#7AC2FF' },
  { id: 'color_lavender', name: 'Lavender Name', description: 'A calm lavender username color.', category: 'usernameColor', rarity: RARITY.COMMON, price: 22, imageName: 'textformat', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#B49AE8' },
  { id: 'color_sunburst', name: 'Sunburst Name', description: 'A golden-to-tangerine gradient name.', category: 'usernameColor', rarity: RARITY.RARE, price: 38, imageName: 'textformat', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#FFD23D', secondaryColorHex: '#FF8C5A' },
  { id: 'color_cherry', name: 'Cherry Cola Name', description: 'A deep cherry-red gradient name.', category: 'usernameColor', rarity: RARITY.RARE, price: 36, imageName: 'textformat', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#E0455C', secondaryColorHex: '#7A1A2E' },
  { id: 'color_royal', name: 'Royal Name', description: 'An indigo-to-violet gradient fit for royalty.', category: 'usernameColor', rarity: RARITY.RARE, price: 38, imageName: 'textformat', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#6B5CE7', secondaryColorHex: '#9B6CE0' },

  // Profile badges
  { id: 'badge_thinker', name: 'Thinker Badge', description: 'A badge for the deep thinker.', category: 'badge', rarity: RARITY.RARE, price: 40, imageName: 'brain.head.profile', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#5C8AD9', bannerText: 'Deep Thinker', bannerColorHex: '#3A5A9E' },
  { id: 'badge_spark', name: 'Spark Badge', description: 'A badge that glows with Spark energy.', category: 'badge', rarity: RARITY.COMMON, price: 18, imageName: 'sparkle', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#7EC8FF', bannerText: 'Spark Master', bannerColorHex: '#4A9AD4' },
  { id: 'badge_coolest', name: 'Coolest Badge', description: 'For debaters with unmatched style.', category: 'badge', rarity: RARITY.RARE, price: 42, imageName: 'sunglasses.fill', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#6B5CE7', bannerText: 'Coolest Debater', bannerColorHex: '#4538A8' },
  { id: 'badge_wordsmith', name: 'Wordsmith Badge', description: 'For those whose words cut sharpest.', category: 'badge', rarity: RARITY.RARE, price: 38, imageName: 'quote.bubble.fill', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#E0915C', bannerText: 'Wordsmith', bannerColorHex: '#A8622F' },
  { id: 'badge_strategist', name: 'Strategist Badge', description: 'Always three arguments ahead.', category: 'badge', rarity: RARITY.RARE, price: 44, imageName: 'chess.board', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#39C0B3', bannerText: 'Strategist', bannerColorHex: '#1E7A70' },
  { id: 'badge_night_owl', name: 'Night Owl Badge', description: 'Sharpest after midnight.', category: 'badge', rarity: RARITY.RARE, price: 40, imageName: 'moon.stars.fill', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#8A9AE8', bannerText: 'Night Owl', bannerColorHex: '#2E3A8C' },
  { id: 'badge_hot_streak', name: 'Hot Streak Badge', description: 'Win after win after win.', category: 'badge', rarity: RARITY.RARE, price: 44, imageName: 'flame.fill', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#FF7A3D', bannerText: 'On Fire', bannerColorHex: '#B33A0F' },
  { id: 'badge_quick_wit', name: 'Quick Wit Badge', description: 'The comeback arrives before the argument lands.', category: 'badge', rarity: RARITY.COMMON, price: 24, imageName: 'bolt.fill', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#FFE03D', bannerText: 'Quick Wit', bannerColorHex: '#B39A0F' },
  { id: 'badge_scholar', name: 'Scholar Badge', description: 'Every claim comes with a citation.', category: 'badge', rarity: RARITY.COMMON, price: 26, imageName: 'books.vertical.fill', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#C98F5C', bannerText: 'Scholar', bannerColorHex: '#7A4E2E' },
  { id: 'badge_sharpshooter', name: 'Sharpshooter Badge', description: 'Every point hits dead center.', category: 'badge', rarity: RARITY.RARE, price: 42, imageName: 'target', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#E0455C', bannerText: 'Sharpshooter', bannerColorHex: '#8A1A2E' },
  { id: 'badge_showman', name: 'Showman Badge', description: 'Debate is a stage — own it.', category: 'badge', rarity: RARITY.RARE, price: 38, imageName: 'theatermasks.fill', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#B06CFF', bannerText: 'Showman', bannerColorHex: '#5C2E9E' },
  { id: 'badge_mic_drop', name: 'Mic Drop Badge', description: 'Say the last word. Walk away.', category: 'badge', rarity: RARITY.RARE, price: 44, imageName: 'music.mic', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#3DC8FF', bannerText: 'Mic Drop', bannerColorHex: '#0F6E9E' },
  { id: 'badge_high_roller', name: 'High Roller Badge', description: 'Fortune favors the bold.', category: 'badge', rarity: RARITY.RARE, price: 40, imageName: 'dice.fill', isAnimated: false, rotationType: 'daily', isLimited: false, colorHex: '#3DE08A', bannerText: 'High Roller', bannerColorHex: '#0F7A44' },

  // ── Weekly items (rotationType: 'weekly', price 75-180) ───────────────
  { id: 'frame_aurora_anim', name: 'Aurora Frame', description: 'An animated aurora avatar ring that shimmers.', category: 'frame', rarity: RARITY.EPIC, price: 120, imageName: 'circle.hexagongrid.fill', isAnimated: true, rotationType: 'weekly', isLimited: false, colorHex: '#7AE0C2', secondaryColorHex: '#7A8CE0', effect: 'shimmer' },
  { id: 'frame_phoenix_anim', name: 'Phoenix Frame', description: 'A legendary animated flame ring.', category: 'frame', rarity: RARITY.LEGENDARY, price: 180, imageName: 'flame.circle.fill', isAnimated: true, rotationType: 'weekly', isLimited: true, colorHex: '#FF7A3D', secondaryColorHex: '#FFD23D', effect: 'glow' },
  { id: 'frame_diamond', name: 'Diamond Frame', description: 'A brilliant diamond-cut avatar ring.', category: 'frame', rarity: RARITY.EPIC, price: 145, imageName: 'diamond.fill', isAnimated: true, rotationType: 'weekly', isLimited: false, colorHex: '#E8F4FF', secondaryColorHex: '#9AC4E8', effect: 'shimmer' },
  { id: 'frame_royal_anim', name: 'Royal Frame', description: 'An animated royal purple-and-gold ring.', category: 'frame', rarity: RARITY.EPIC, price: 130, imageName: 'crown.fill', isAnimated: true, rotationType: 'weekly', isLimited: false, colorHex: '#8A5CE0', secondaryColorHex: '#E0C25C', effect: 'shimmer' },
  { id: 'color_prismatic', name: 'Prismatic Name', description: 'A vivid prismatic username color.', category: 'usernameColor', rarity: RARITY.EPIC, price: 90, imageName: 'textformat', isAnimated: true, rotationType: 'weekly', isLimited: false, colorHex: '#B06CFF', secondaryColorHex: '#5CC8E0', effect: 'shimmer' },
  { id: 'color_neon_pulse', name: 'Neon Pulse Name', description: 'An electric neon name that softly pulses.', category: 'usernameColor', rarity: RARITY.EPIC, price: 95, imageName: 'textformat', isAnimated: true, rotationType: 'weekly', isLimited: false, colorHex: '#3DFFB0', secondaryColorHex: '#3DC8FF', effect: 'pulse' },
  { id: 'badge_champion', name: 'Champion Badge', description: 'A rare champion badge for your profile.', category: 'badge', rarity: RARITY.EPIC, price: 95, imageName: 'trophy.fill', isAnimated: false, rotationType: 'weekly', isLimited: false, colorHex: '#C9A962', bannerText: 'Champion', bannerColorHex: '#9A7B3A', effect: 'glow' },
  { id: 'badge_legend', name: 'Legend Badge', description: 'For debaters who never back down.', category: 'badge', rarity: RARITY.LEGENDARY, price: 125, imageName: 'star.circle.fill', isAnimated: false, rotationType: 'weekly', isLimited: false, colorHex: '#FFB347', bannerText: 'Legend', bannerColorHex: '#CC7A1A', effect: 'shimmer' },
  { id: 'badge_gladiator', name: 'Gladiator Badge', description: 'An animated badge forged for the arena of ideas.', category: 'badge', rarity: RARITY.EPIC, price: 110, imageName: 'shield.lefthalf.filled', isAnimated: true, rotationType: 'weekly', isLimited: false, colorHex: '#D95C5C', bannerText: 'Gladiator', bannerColorHex: '#8A2E2E', effect: 'shimmer' },
  { id: 'frame_dragonfire', name: 'Dragonfire Frame', description: 'A legendary ring wreathed in living dragonflame.', category: 'frame', rarity: RARITY.LEGENDARY, price: 175, imageName: 'flame.fill', isAnimated: true, rotationType: 'weekly', isLimited: true, colorHex: '#FF4D2E', secondaryColorHex: '#FFB347', effect: 'glow' },
  { id: 'frame_tidal', name: 'Tidal Frame', description: 'An animated ring of rolling ocean surf.', category: 'frame', rarity: RARITY.EPIC, price: 125, imageName: 'water.waves', isAnimated: true, rotationType: 'weekly', isLimited: false, colorHex: '#2E8CFF', secondaryColorHex: '#7AE0C2', effect: 'shimmer' },
  { id: 'frame_voltage', name: 'Voltage Frame', description: 'A crackling high-voltage ring that pulses with charge.', category: 'frame', rarity: RARITY.EPIC, price: 135, imageName: 'bolt.circle.fill', isAnimated: true, rotationType: 'weekly', isLimited: false, colorHex: '#F5FF3D', secondaryColorHex: '#3DC8FF', effect: 'pulse' },
  { id: 'frame_blossom', name: 'Blossom Frame', description: 'An animated ring of drifting cherry-blossom petals.', category: 'frame', rarity: RARITY.EPIC, price: 115, imageName: 'leaf.fill', isAnimated: true, rotationType: 'weekly', isLimited: false, colorHex: '#FF9AC2', secondaryColorHex: '#FFD9E8', effect: 'shimmer' },
  { id: 'frame_obsidian_gold', name: 'Obsidian Gold Frame', description: 'A legendary black-glass ring veined with molten gold.', category: 'frame', rarity: RARITY.LEGENDARY, price: 170, imageName: 'circle.circle.fill', isAnimated: true, rotationType: 'weekly', isLimited: true, colorHex: '#1A1A24', secondaryColorHex: '#FFD700', effect: 'shimmer' },
  { id: 'frame_cyber', name: 'Cyber Frame', description: 'A neon cyberpunk ring straight from 2099.', category: 'frame', rarity: RARITY.EPIC, price: 140, imageName: 'cpu.fill', isAnimated: true, rotationType: 'weekly', isLimited: false, colorHex: '#FF2ED9', secondaryColorHex: '#2EF5FF', effect: 'shimmer' },
  { id: 'color_galaxy', name: 'Galaxy Name', description: 'A name swirling with violet-and-blue starlight.', category: 'usernameColor', rarity: RARITY.EPIC, price: 95, imageName: 'textformat', isAnimated: true, rotationType: 'weekly', isLimited: false, colorHex: '#B06CFF', secondaryColorHex: '#2E8CFF', effect: 'shimmer' },
  { id: 'color_bloodmoon', name: 'Blood Moon Name', description: 'A name glowing with eclipse-red light.', category: 'usernameColor', rarity: RARITY.EPIC, price: 92, imageName: 'textformat', isAnimated: true, rotationType: 'weekly', isLimited: false, colorHex: '#FF3D5C', secondaryColorHex: '#4A0A14', effect: 'glow' },
  { id: 'color_goldenhour', name: 'Golden Hour Name', description: 'A legendary name bathed in sunset gold.', category: 'usernameColor', rarity: RARITY.LEGENDARY, price: 120, imageName: 'textformat', isAnimated: true, rotationType: 'weekly', isLimited: true, colorHex: '#FFD700', secondaryColorHex: '#FF8C5A', effect: 'shimmer' },
  { id: 'color_vaporwave', name: 'Vaporwave Name', description: 'A retro neon name that pulses pink and cyan.', category: 'usernameColor', rarity: RARITY.EPIC, price: 98, imageName: 'textformat', isAnimated: true, rotationType: 'weekly', isLimited: false, colorHex: '#FF71CE', secondaryColorHex: '#01CDFE', effect: 'pulse' },
  { id: 'color_toxic', name: 'Toxic Name', description: 'A radioactive green name with a hazardous glow.', category: 'usernameColor', rarity: RARITY.EPIC, price: 90, imageName: 'textformat', isAnimated: true, rotationType: 'weekly', isLimited: false, colorHex: '#B4FF3D', secondaryColorHex: '#3DFF8C', effect: 'glow' },
  { id: 'badge_dragon_heart', name: 'Dragon Heart Badge', description: 'A legendary badge that beats with dragonfire.', category: 'badge', rarity: RARITY.LEGENDARY, price: 160, imageName: 'flame.circle.fill', isAnimated: true, rotationType: 'weekly', isLimited: true, colorHex: '#FF4D2E', bannerText: 'Dragon Heart', bannerColorHex: '#7A1A0F', effect: 'glow' },
  { id: 'badge_crowned', name: 'Crowned Badge', description: 'Some argue for sport. You argue for the throne.', category: 'badge', rarity: RARITY.EPIC, price: 105, imageName: 'crown.fill', isAnimated: false, rotationType: 'weekly', isLimited: false, colorHex: '#FFD23D', bannerText: 'Crowned', bannerColorHex: '#9A7B0A', effect: 'shimmer' },
  { id: 'badge_storm_caller', name: 'Storm Caller Badge', description: 'An animated badge that summons the tempest.', category: 'badge', rarity: RARITY.EPIC, price: 110, imageName: 'cloud.bolt.fill', isAnimated: true, rotationType: 'weekly', isLimited: false, colorHex: '#7AC2FF', bannerText: 'Storm Caller', bannerColorHex: '#2E4A8C', effect: 'pulse' },
  { id: 'badge_mastermind', name: 'Mastermind Badge', description: 'Every debate was decided before it began.', category: 'badge', rarity: RARITY.EPIC, price: 108, imageName: 'atom', isAnimated: true, rotationType: 'weekly', isLimited: false, colorHex: '#5CE0D0', bannerText: 'Mastermind', bannerColorHex: '#1E7A70', effect: 'shimmer' },
  { id: 'badge_untouchable', name: 'Untouchable Badge', description: 'A legendary badge for records without a scratch.', category: 'badge', rarity: RARITY.LEGENDARY, price: 150, imageName: 'shield.checkered', isAnimated: true, rotationType: 'weekly', isLimited: true, colorHex: '#E8F4FF', bannerText: 'Untouchable', bannerColorHex: '#3A5A9E', effect: 'shimmer' },
  { id: 'badge_goat', name: 'G.O.A.T. Badge', description: 'A legendary laurel for the greatest of all time.', category: 'badge', rarity: RARITY.LEGENDARY, price: 165, imageName: 'laurel.trailing', isAnimated: true, rotationType: 'weekly', isLimited: true, colorHex: '#FFB347', bannerText: 'G.O.A.T.', bannerColorHex: '#8A5A0F', effect: 'shimmer' },

  // ── Special items (rotationType: 'special', price 200-500) ─────────────
  // Ultra-rare finds. Only occasionally appear in a user's personal daily
  // shop ("Rare Find" slot), so spotting one feels like an event.
  { id: 'frame_galaxy_mythic', name: 'Galaxy Frame', description: 'A mythic animated ring of swirling starlight. Almost never in stock.', category: 'frame', rarity: RARITY.MYTHIC, price: 450, imageName: 'sparkles', isAnimated: true, rotationType: 'special', isLimited: true, colorHex: '#7A5CFF', secondaryColorHex: '#FF5CD0', effect: 'rainbow' },
  { id: 'frame_eclipse_mythic', name: 'Eclipse Frame', description: 'A mythic ring of molten gold circling the dark.', category: 'frame', rarity: RARITY.MYTHIC, price: 420, imageName: 'circle.circle.fill', isAnimated: true, rotationType: 'special', isLimited: true, colorHex: '#FFD23D', secondaryColorHex: '#1A1A24', effect: 'glow' },
  { id: 'color_aurora_mythic', name: 'Aurora Name', description: 'A mythic name that flows through the colors of the northern lights.', category: 'usernameColor', rarity: RARITY.MYTHIC, price: 380, imageName: 'textformat', isAnimated: true, rotationType: 'special', isLimited: true, colorHex: '#3DFFB0', secondaryColorHex: '#B06CFF', effect: 'rainbow' },
  { id: 'badge_immortal_mythic', name: 'Immortal Badge', description: 'A mythic badge reserved for the rarest of debaters.', category: 'badge', rarity: RARITY.MYTHIC, price: 500, imageName: 'laurel.leading', isAnimated: true, rotationType: 'special', isLimited: true, colorHex: '#FF5CD0', bannerText: 'Immortal', bannerColorHex: '#7A1A5C', effect: 'rainbow' },
  { id: 'badge_founder_gold', name: 'Golden Founder Badge', description: 'A legendary badge dipped in pure gold, with a moving sheen.', category: 'badge', rarity: RARITY.LEGENDARY, price: 260, imageName: 'medal.fill', isAnimated: true, rotationType: 'special', isLimited: true, colorHex: '#FFD700', bannerText: 'Golden Founder', bannerColorHex: '#8A6A00', effect: 'shimmer' },
  { id: 'frame_void_mythic', name: 'Void Frame', description: 'A mythic ring of pure darkness, edged in violet light that should not exist.', category: 'frame', rarity: RARITY.MYTHIC, price: 460, imageName: 'circle.dashed', isAnimated: true, rotationType: 'special', isLimited: true, colorHex: '#0A0A14', secondaryColorHex: '#6B2EFF', effect: 'glow' },
  { id: 'frame_supernova_mythic', name: 'Supernova Frame', description: 'A mythic ring caught mid-explosion — a dying star around your avatar.', category: 'frame', rarity: RARITY.MYTHIC, price: 480, imageName: 'sun.max.fill', isAnimated: true, rotationType: 'special', isLimited: true, colorHex: '#FFF3A0', secondaryColorHex: '#FF5C2E', effect: 'rainbow' },
  { id: 'color_singularity_mythic', name: 'Singularity Name', description: 'A mythic name that bends every color of light around it.', category: 'usernameColor', rarity: RARITY.MYTHIC, price: 400, imageName: 'textformat', isAnimated: true, rotationType: 'special', isLimited: true, colorHex: '#6B2EFF', secondaryColorHex: '#FF5CD0', effect: 'rainbow' },
  { id: 'badge_celestial_mythic', name: 'Celestial Badge', description: 'A mythic badge written in constellations.', category: 'badge', rarity: RARITY.MYTHIC, price: 470, imageName: 'moon.stars.fill', isAnimated: true, rotationType: 'special', isLimited: true, colorHex: '#9AC4E8', bannerText: 'Celestial', bannerColorHex: '#2E3A8C', effect: 'rainbow' },
  { id: 'badge_kingmaker', name: 'Kingmaker Badge', description: 'A legendary badge for those who decide who wins.', category: 'badge', rarity: RARITY.LEGENDARY, price: 280, imageName: 'checkmark.seal.fill', isAnimated: true, rotationType: 'special', isLimited: true, colorHex: '#C9A962', bannerText: 'Kingmaker', bannerColorHex: '#6B4A0F', effect: 'shimmer' },

  // ── Limited run (limitedStock) ──────────────────────────────────────────
  // Exactly `limitedStock` copies exist worldwide. The purchase endpoint
  // increments `soldCount` on the shopItems doc inside the purchase
  // transaction; once soldCount reaches limitedStock the item is gone
  // forever. NOTE: never put `soldCount` in this catalog — the deploy-time
  // sync would reset the live counter.
  //
  // There is exactly ONE limited item at a time. It does NOT rotate — it
  // stays in the shop until it sells out or is manually replaced here.
  { id: 'frame_first_edition', name: 'First Edition Frame', description: 'A numbered first-edition ring in rose gold and platinum. Only 999 will ever be minted.', category: 'frame', rarity: RARITY.LEGENDARY, price: 850, imageName: 'seal.fill', isAnimated: true, rotationType: 'limited', isLimited: true, limitedStock: 999, colorHex: '#E8A9A0', secondaryColorHex: '#E8F4FF', effect: 'shimmer' }
];

module.exports = { CATALOG, RARITY };
